LIB_DIR=$1
CPP_NAME=$2
MODEL_FILE_DIR=$3
INPUT_PATH=$4
WITH_MKL=$5
WITH_GPU=$6
CUDNN_LIB=$7
CUDA_LIB=$8
USE_TENSORRT=$9
TENSORRT_ROOT=$10

mkdir -p build_${CPP_NAME}
cd build_${CPP_NAME}
rm -rf *

cmake .. -DPADDLE_LIB=${LIB_DIR} \
  -DWITH_MKL=${WITH_MKL} \
  -DDEMO_NAME=${CPP_NAME} \
  -DWITH_GPU=${WITH_GPU} \
  -DWITH_STATIC_LIB=OFF \
  -DUSE_TENSORRT=${USE_TENSORRT} \
  -DCUDNN_LIB=${CUDNN_LIB} \
  -DCUDA_LIB=${CUDA_LIB} \
  -DTENSORRT_ROOT=${TENSORRT_ROOT}

make -j

./${CPP_NAME} --model_path=${MODEL_FILE_DIR} --input_path=${INPUT_PATH}
